name: flutter_notes_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: 7.3.0

  json_annotation: 4.8.0
  equatable: 2.0.5
  go_router: 7.1.1
  intl: 0.18.1

  firebase_core: 2.14.0
  cloud_firestore: ^4.8.2
  firebase_auth: 4.6.3
  google_sign_in: 6.1.4

  my_foundation:
    git:
      url: https://github.com/HenriqueWojcik/my_foundation
      ref: main

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: 2.3.3
  json_serializable: 6.6.1
  mockito: ^5.4.3
  fake_cloud_firestore: ^2.4.1+1
  faker: ^2.1.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/mocks/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
