// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5rt_fRZc2BzmhlZqqYZah3eGlLIBrtzQ',
    appId: '1:737186218911:android:a3c8613bf8965ec22773aa',
    messagingSenderId: '737186218911',
    projectId: 'flutter-notes-app-7ef66',
    storageBucket: 'flutter-notes-app-7ef66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBloszSMDBw5NQMx8XJUai3yG1LkaUk5LY',
    appId: '1:737186218911:ios:fe1f11dada0063872773aa',
    messagingSenderId: '737186218911',
    projectId: 'flutter-notes-app-7ef66',
    storageBucket: 'flutter-notes-app-7ef66.firebasestorage.app',
    androidClientId: '737186218911-37al98lg7bpp9evk9vagq3224i8phraf.apps.googleusercontent.com',
    iosClientId: '737186218911-7vi2u5vvqjp49bmttph30tk5gnmukjmu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterNotesApp',
  );
}
